### ISSUE TITLE
Playlist Download

### ISSUE THREAD

**Issue by jonjieviduya** [DevinNorgarb/devtube#4]
Can we also have an option where we can download a playlist?

**Comment by DevinNorgarb** [comment]
Hi @jonjieviduya , I am sure I built that functionality in. I don't think I ever got around to documenting it. however.If I didn't I will add the ability to download playlists I have some spare time. 

Will keep you updated!
Cheers

**Comment by anthonyinit** [comment]
Hello,
Is this still working?

**Comment by DevinNorgarb** [comment]
Hi @jonjieviduya @anthonyinit ,

Devtube Downloader will download playlists, just pass the playlist URL like below: 
`https://www.youtube.com/watch?v=HQmmM_qwG4k&list=RDEMo1pnOuN0J4ZzmIfrwxpP0w`

Make sure the the URL has both a `?v=random_id` and a `&list=` parameter.

It will just start downloading each video one by one from the playlist.

The below example works for me:

`Route::get('/download', function () {

    $dl = new Download($url = "https://www.youtube.com/watch?v=HQmmM_qwG4k&list=RDEMo1pnOuN0J4ZzmIfrwxpP0w", $format = "mp4", $download_path = "app");
    //Saves the file to specified directory
    $media_info = $dl->download();
    $media_info = $media_info->first();

    // Return as a download
    dd($media_info);
    return response()->download($media_info['file']->getPathname());
});`

**Comment by DevinNorgarb** [comment]
@jonjieviduya 
Please let me know if using a playlist URL works, if so then I will close this issue.
Thanks.

Sidenote: would anyone like to see the addition of helper methods? Maybe something that could return all the urls/video ids for a playlist just by passing the `&list=playlist_id`.  Just a thought.

**Comment by anthonyinit** [comment]
It is working :)
